project_param:
  input_foldername: "input"

bq_param:
  project_id: "placeholder_project_id"
  dataset: "placeholder_dataset"
  tablename: "placeholder_tablename"

file_param:
  file_relative_path: ""  # Leave empty if not needed
  file_radcname: "incoming_excel_filename"
  file_ext: ".xlsx"
  sheet_name: "incoming_excel_filename"