project_param:
  data_incoming_foldername: ""      # Optional: specify folder for incoming data
  data_outgoing_foldername: ""      # Optional: specify folder for outgoing data

bq_param:
  project_id: "mtb-eu-datalake-ww-nprd"  # Google Cloud project ID
  dataset: "finance"                     # BigQuery dataset name
  tablename: ""                          # BigQuery table name (to be specified)

file_param:
  file_relative_path: ""                # Optional: relative path within the project
  file_radcname: ""                     # Base name of the file (without extension)
  file_ext: ""                          # File extension (e.g., .csv, .xlsx, .parquet)
  sheet_name: ""                        # Sheet name in the Excel file (required for .xlsx)